"""primera migracion

Revision ID: ed2902de0a35
Revises: 
Create Date: 2025-11-24 21:03:25.789168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2902de0a35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ESTADOS_ALQUILER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ESTADOS_ALQUILER_fecha_creacion'), 'ESTADOS_ALQUILER', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_ESTADOS_ALQUILER_fecha_modificacion'), 'ESTADOS_ALQUILER', ['fecha_modificacion'], unique=False)
    op.create_index(op.f('ix_ESTADOS_ALQUILER_id'), 'ESTADOS_ALQUILER', ['id'], unique=False)
    op.create_table('ESTADOS_AUTO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ESTADOS_AUTO_fecha_creacion'), 'ESTADOS_AUTO', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_ESTADOS_AUTO_fecha_modificacion'), 'ESTADOS_AUTO', ['fecha_modificacion'], unique=False)
    op.create_index(op.f('ix_ESTADOS_AUTO_id'), 'ESTADOS_AUTO', ['id'], unique=False)
    op.create_table('ROLES_USUARIOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ROLES_USUARIOS_fecha_creacion'), 'ROLES_USUARIOS', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_ROLES_USUARIOS_fecha_modificacion'), 'ROLES_USUARIOS', ['fecha_modificacion'], unique=False)
    op.create_index(op.f('ix_ROLES_USUARIOS_id'), 'ROLES_USUARIOS', ['id'], unique=False)
    op.create_table('AUTOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_alta', sa.String(), nullable=True),
    sa.Column('fecha_baja', sa.String(), nullable=True),
    sa.Column('precio_diario', sa.String(), nullable=True),
    sa.Column('marca', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('patente', sa.Integer(), nullable=True),
    sa.Column('kilometros', sa.Integer(), nullable=False),
    sa.Column('id_estado_auto', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_estado_auto'], ['ESTADOS_AUTO.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patente')
    )
    op.create_index(op.f('ix_AUTOS_fecha_creacion'), 'AUTOS', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_AUTOS_fecha_modificacion'), 'AUTOS', ['fecha_modificacion'], unique=False)
    op.create_index(op.f('ix_AUTOS_id'), 'AUTOS', ['id'], unique=False)
    op.create_table('USUARIOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('contraseña', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('carnet_conducir', sa.Boolean(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['ROLES_USUARIOS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contraseña'),
    sa.UniqueConstraint('dni')
    )
    op.create_index(op.f('ix_USUARIOS_fecha_creacion'), 'USUARIOS', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_USUARIOS_fecha_modificacion'), 'USUARIOS', ['fecha_modificacion'], unique=False)
    op.create_index(op.f('ix_USUARIOS_id'), 'USUARIOS', ['id'], unique=False)
    op.create_table('ALQUILERES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('monto_acordado', sa.Float(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('id_estado_alquiler', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_auto', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_auto'], ['AUTOS.id'], ),
    sa.ForeignKeyConstraint(['id_estado_alquiler'], ['ESTADOS_ALQUILER.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ALQUILERES_fecha_creacion'), 'ALQUILERES', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_ALQUILERES_fecha_modificacion'), 'ALQUILERES', ['fecha_modificacion'], unique=False)
    op.create_index(op.f('ix_ALQUILERES_id'), 'ALQUILERES', ['id'], unique=False)
    op.create_table('MANTENIMIENTOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('detalle', sa.String(), nullable=False),
    sa.Column('id_auto', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_auto'], ['AUTOS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MANTENIMIENTOS_fecha_creacion'), 'MANTENIMIENTOS', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_MANTENIMIENTOS_fecha_modificacion'), 'MANTENIMIENTOS', ['fecha_modificacion'], unique=False)
    op.create_index(op.f('ix_MANTENIMIENTOS_id'), 'MANTENIMIENTOS', ['id'], unique=False)
    op.create_table('PAGOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('metodo', sa.String(), nullable=False),
    sa.Column('id_alquiler', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_alquiler'], ['ALQUILERES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PAGOS_fecha_creacion'), 'PAGOS', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_PAGOS_fecha_modificacion'), 'PAGOS', ['fecha_modificacion'], unique=False)
    op.create_index(op.f('ix_PAGOS_id'), 'PAGOS', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PAGOS_id'), table_name='PAGOS')
    op.drop_index(op.f('ix_PAGOS_fecha_modificacion'), table_name='PAGOS')
    op.drop_index(op.f('ix_PAGOS_fecha_creacion'), table_name='PAGOS')
    op.drop_table('PAGOS')
    op.drop_index(op.f('ix_MANTENIMIENTOS_id'), table_name='MANTENIMIENTOS')
    op.drop_index(op.f('ix_MANTENIMIENTOS_fecha_modificacion'), table_name='MANTENIMIENTOS')
    op.drop_index(op.f('ix_MANTENIMIENTOS_fecha_creacion'), table_name='MANTENIMIENTOS')
    op.drop_table('MANTENIMIENTOS')
    op.drop_index(op.f('ix_ALQUILERES_id'), table_name='ALQUILERES')
    op.drop_index(op.f('ix_ALQUILERES_fecha_modificacion'), table_name='ALQUILERES')
    op.drop_index(op.f('ix_ALQUILERES_fecha_creacion'), table_name='ALQUILERES')
    op.drop_table('ALQUILERES')
    op.drop_index(op.f('ix_USUARIOS_id'), table_name='USUARIOS')
    op.drop_index(op.f('ix_USUARIOS_fecha_modificacion'), table_name='USUARIOS')
    op.drop_index(op.f('ix_USUARIOS_fecha_creacion'), table_name='USUARIOS')
    op.drop_table('USUARIOS')
    op.drop_index(op.f('ix_AUTOS_id'), table_name='AUTOS')
    op.drop_index(op.f('ix_AUTOS_fecha_modificacion'), table_name='AUTOS')
    op.drop_index(op.f('ix_AUTOS_fecha_creacion'), table_name='AUTOS')
    op.drop_table('AUTOS')
    op.drop_index(op.f('ix_ROLES_USUARIOS_id'), table_name='ROLES_USUARIOS')
    op.drop_index(op.f('ix_ROLES_USUARIOS_fecha_modificacion'), table_name='ROLES_USUARIOS')
    op.drop_index(op.f('ix_ROLES_USUARIOS_fecha_creacion'), table_name='ROLES_USUARIOS')
    op.drop_table('ROLES_USUARIOS')
    op.drop_index(op.f('ix_ESTADOS_AUTO_id'), table_name='ESTADOS_AUTO')
    op.drop_index(op.f('ix_ESTADOS_AUTO_fecha_modificacion'), table_name='ESTADOS_AUTO')
    op.drop_index(op.f('ix_ESTADOS_AUTO_fecha_creacion'), table_name='ESTADOS_AUTO')
    op.drop_table('ESTADOS_AUTO')
    op.drop_index(op.f('ix_ESTADOS_ALQUILER_id'), table_name='ESTADOS_ALQUILER')
    op.drop_index(op.f('ix_ESTADOS_ALQUILER_fecha_modificacion'), table_name='ESTADOS_ALQUILER')
    op.drop_index(op.f('ix_ESTADOS_ALQUILER_fecha_creacion'), table_name='ESTADOS_ALQUILER')
    op.drop_table('ESTADOS_ALQUILER')
    # ### end Alembic commands ###
